### ISSUE TITLE
Problem with example stream-payments

### ISSUE THREAD

**Issue by congnghiakhiem** [zulucrypto/stellar-api#19]
D:\temp\stellar-api-master\examples>php stream-payments.php
[2018-06-26 07:59:36am] f18e7a7b61fae788a66806392f7b7292294450bc81e29932b3f4a84864df74b2 from 0.1000000 DRA -> GCZIHCK7VADIB6QQBV74GYVYWJ2RHGZANOPFTEIM2Q256WQUIKYICOBV
[2018-06-26 07:59:36am] c53bab0aeb487f0c2bb12f3996443e0ae9bbf5f822fd765f29a556bb3152dc4f from 0.1000000 DRA -> GAMOD4OB2HPK6CJSP4GYQCUKE4ZYCZAFOWBDA7ZH5KL63GGGLKFFFGFN
[2018-06-26 07:59:36am] d09fbc878aba02662528a4e5ff1aba854fe1d99a4af83902008c992c9ca88989 from 0.1000000 DRA -> GC2TFRQMFMRRT47HJKPYKNRY5CZWIPRHLFNJ3XOJRWZJPBUYX2DGGHIV
[2018-06-26 07:59:36am] c8c8df7572739e08eb12a269cfc8b46f939227be6c336ca9e1b97129289e0566 from 0.1000000 DRA -> GA5GQZ4UC2MGKB42JTCPOZS44Y2QMQOEKQY5I7O6XFHP5O6ABDDARHIY
[2018-06-26 07:59:36am] 23f818640bd8df914e91de98a476daef5aca18df8300ec763bcf9eb91869ae5d from 0.1000000 DRA -> GDNAACGF76ZHPDBEHOXOHI6T6TJ76PUBNGPY5HT35Q7WPFAJRR4RPOU5
[2018-06-26 07:59:36am] c791fed4835551168a0623e3230212e4ca8b71c38040a5a2b06b82f0d4302f2d from 0.1000000 DRA -> GCZXN7G7ECXXJJOQ4X6OOFDLFE7EYYQMVYVJ57TAPJ5IERB75TQHZLUK
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of ZuluCrypto\StellarSdk\Model\Payment, instance of ZuluCrypto\StellarSdk\Model\CreateAccountOperation given, called in D:\temp\stellar-api-master\src\Horizon\ApiClient.php on line 382 and defined in D:\temp\stellar-api-master\examples\stream-payments.php:10
Stack trace:
#0 D:\temp\stellar-api-master\src\Horizon\ApiClient.php(382): {closure}(Object(ZuluCrypto\StellarSdk\Model\CreateAccountOperation))
#1 D:\temp\stellar-api-master\src\Horizon\ApiClient.php(464): ZuluCrypto\StellarSdk\Horizon\ApiClient->ZuluCrypto\StellarSdk\Horizon\{closure}(Array)
#2 D:\temp\stellar-api-master\src\Horizon\ApiClient.php(383): ZuluCrypto\StellarSdk\Horizon\ApiClient->getAndStream('/payments?curso...', Object(Closure))
#3 D:\temp\stellar-api-master\examples\stream-payments.php(18): ZuluCrypto\StellarSdk\Horizon\ApiClient->streamPayments('now', Object(Closure))
#4 {main}
  thrown in D:\temp\stellar-api-master\examples\stream-payments.php on line 10

**Comment by zulucrypto** [comment]
Thanks for reporting this, I'm working on a maintenance release and will make sure a fix for this gets in there

**Comment by congnghiakhiem** [comment]
PHP 7.0.30 (cli) (built: Apr 24 2018 16:16:46) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

stellar-api
### 0.6.3

Windows 10

**Comment by zulucrypto** [comment]
Fixed in 0.6.4
