### ISSUE TITLE
Uncaught ErrorException: Unknown error code 1  CreateAccountResult.php

### ISSUE THREAD

**Issue by minherc** [zulucrypto/stellar-api#47]
I received code 1 and code 3 errors.
Strange but this when I did manage offer
i do ZuluCrypto\StellarSdk\XdrModel\Operation\ManageOfferOp
but error in CreateAccountResult.php:39
how is it?
```
Array
(
    [nominator] => 222
    [denominator] => 1
    [str_view] => 222/1
)
asset_code_b: ETHM

Array
(
    [nominator] => 19979
    [denominator] => 35308
    [str_view] => 19979/35308
)
asset_code_b: XLM

Array
(
    [nominator] => 283
    [denominator] => 622132
    [str_view] => 283/622132
)
asset_code_b: BTCM

Array
(
    [nominator] => 217019
    [denominator] => 13077
    [str_view] => 217019/13077
)


Fatal error:  Uncaught ErrorException: Unknown error code 1 in /var/www/html/stellar-api/src/XdrModel/CreateAccountResult.php:39
Stack trace:
#0 /var/www/html/stellar-api/src/XdrModel/OperationResult.php(49): ZuluCrypto\StellarSdk\XdrModel\CreateAccountResult::fromXdr(Object(ZuluCrypto\StellarSdk\Xdr\XdrBuffer))
#1 /var/www/html/stellar-api/src/XdrModel/TransactionResult.php(83): ZuluCrypto\StellarSdk\XdrModel\OperationResult::fromXdr(Object(ZuluCrypto\StellarSdk\Xdr\XdrBuffer))
#2 /var/www/html/stellar-api/src/Horizon/Api/PostTransactionResponse.php(45): ZuluCrypto\StellarSdk\XdrModel\TransactionResult::fromXdr(Object(ZuluCrypto\StellarSdk\Xdr\XdrBuffer))
#3 /var/www/html/stellar-api/src/Horizon/Api/PostTransactionResponse.php(30): ZuluCrypto\StellarSdk\Horizon\Api\PostTransactionResponse->parseRawData(Array)
#4 /var/www/html/stellar-api/src/Horizon/ApiClient.php(508): ZuluCrypto\StellarSdk\Horizon\Api\PostTransactionResponse->__construct(Object(GuzzleHttp\Psr7\Stream))
#5 /var/www/html/stellar-api/src/Horizon/ApiClient.p in /var/www/html/stellar-api/src/XdrModel/CreateAccountResult.php on line 39

```

**Comment by minherc** [comment]
```
Array
(
    [nominator] => 222
    [denominator] => 1
    [str_view] => 222/1
)
asset_code_b: ETHM

Array
(
    [nominator] => 23405
    [denominator] => 41419
    [str_view] => 23405/41419
)
asset_code_b: XLM

Array
(
    [nominator] => 6356
    [denominator] => 13850213
    [str_view] => 6356/13850213
)
asset_code_b: BTCM

Array
(
    [nominator] => 131699
    [denominator] => 7935
    [str_view] => 131699/7935
)


Fatal error:  Uncaught ErrorException: Unknown error code 3 in /var/www/html/stellar-api/src/XdrModel/CreateAccountResult.php:41
Stack trace:
#0 /var/www/html/stellar-api/src/XdrModel/OperationResult.php(49): ZuluCrypto\StellarSdk\XdrModel\CreateAccountResult::fromXdr(Object(ZuluCrypto\StellarSdk\Xdr\XdrBuffer))
#1 /var/www/html/stellar-api/src/XdrModel/TransactionResult.php(83): ZuluCrypto\StellarSdk\XdrModel\OperationResult::fromXdr(Object(ZuluCrypto\StellarSdk\Xdr\XdrBuffer))
#2 /var/www/html/stellar-api/src/Horizon/Api/PostTransactionResponse.php(45): ZuluCrypto\StellarSdk\XdrModel\TransactionResult::fromXdr(Object(ZuluCrypto\StellarSdk\Xdr\XdrBuffer))
#3 /var/www/html/stellar-api/src/Horizon/Api/PostTransactionResponse.php(30): ZuluCrypto\StellarSdk\Horizon\Api\PostTransactionResponse->parseRawData(Array)
#4 /var/www/html/stellar-api/src/Horizon/ApiClient.php(508): ZuluCrypto\StellarSdk\Horizon\Api\PostTransactionResponse->__construct(Object(GuzzleHttp\Psr7\Stream))
#5 /var/www/html/stellar-api/src/Horizon/ApiClient.p in /var/www/html/stellar-api/src/XdrModel/CreateAccountResult.php on line 41

```

**Comment by minherc** [comment]
DUMP object to submit 

```
ZuluCrypto\StellarSdk\Transaction\TransactionBuilder Object
(
    [accountId:ZuluCrypto\StellarSdk\Transaction\TransactionBuilder:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
        (
            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
        )

    [timeBounds:ZuluCrypto\StellarSdk\Transaction\TransactionBuilder:private] => ZuluCrypto\StellarSdk\XdrModel\TimeBounds Object
        (
            [minTime:ZuluCrypto\StellarSdk\XdrModel\TimeBounds:private] => 
            [maxTime:ZuluCrypto\StellarSdk\XdrModel\TimeBounds:private] => 
        )

    [memo:ZuluCrypto\StellarSdk\Transaction\TransactionBuilder:private] => ZuluCrypto\StellarSdk\XdrModel\Memo Object
        (
            [type:ZuluCrypto\StellarSdk\XdrModel\Memo:private] => 0
            [value:ZuluCrypto\StellarSdk\XdrModel\Memo:private] => 
        )

    [operations:ZuluCrypto\StellarSdk\Transaction\TransactionBuilder:private] => ZuluCrypto\StellarSdk\Xdr\Type\VariableArray Object
        (
            [elements:ZuluCrypto\StellarSdk\Xdr\Type\VariableArray:private] => Array
                (
                    [0] => ZuluCrypto\StellarSdk\XdrModel\Operation\ManageOfferOp Object
                        (
                            [sellingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 1
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => MERA
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
                                        (
                                            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
                                            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
                                            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
                                        )

                                )

                            [buyingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 1
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => USDM
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
                                        (
                                            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
                                            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
                                            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
                                        )

                                )

                            [amount:protected] => ZuluCrypto\StellarSdk\Model\StellarAmount Object
                                (
                                    [stroops:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x00939a85c40939a6
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [stroopScaleBignum:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x00989680
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [maxSignedStroops64:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x7fffffffffffffff
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                )

                            [price:protected] => ZuluCrypto\StellarSdk\XdrModel\Price Object
                                (
                                    [numerator:protected] => 222
                                    [denominator:protected] => 1
                                )

                            [offerId:protected] => 73961157
                            [sourceAccount:protected] => 
                            [type:protected] => 3
                        )

                    [1] => ZuluCrypto\StellarSdk\XdrModel\Operation\ManageOfferOp Object
                        (
                            [sellingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 1
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => MERA
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
                                        (
                                            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
                                            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
                                            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
                                        )

                                )

                            [buyingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 1
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ETHM
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
                                        (
                                            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
                                            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
                                            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
                                        )

                                )

                            [amount:protected] => ZuluCrypto\StellarSdk\Model\StellarAmount Object
                                (
                                    [stroops:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x0de0b6b3a6cb6980
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [stroopScaleBignum:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x00989680
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [maxSignedStroops64:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x7fffffffffffffff
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                )

                            [price:protected] => ZuluCrypto\StellarSdk\XdrModel\Price Object
                                (
                                    [numerator:protected] => 25099
                                    [denominator:protected] => 44400
                                )

                            [offerId:protected] => 73961475
                            [sourceAccount:protected] => 
                            [type:protected] => 3
                        )

                    [2] => ZuluCrypto\StellarSdk\XdrModel\Operation\ManageOfferOp Object
                        (
                            [sellingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 1
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => MERA
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
                                        (
                                            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
                                            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
                                            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
                                        )

                                )

                            [buyingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 0
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 
                                )

                            [amount:protected] => ZuluCrypto\StellarSdk\Model\StellarAmount Object
                                (
                                    [stroops:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x0de0b6b3a763e6f7
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [stroopScaleBignum:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x00989680
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [maxSignedStroops64:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x7fffffffffffffff
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                )

                            [price:protected] => ZuluCrypto\StellarSdk\XdrModel\Price Object
                                (
                                    [numerator:protected] => 1105
                                    [denominator:protected] => 2418706
                                )

                            [offerId:protected] => 74263305
                            [sourceAccount:protected] => 
                            [type:protected] => 3
                        )

                    [3] => ZuluCrypto\StellarSdk\XdrModel\Operation\ManageOfferOp Object
                        (
                            [sellingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 1
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => MERA
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
                                        (
                                            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
                                            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
                                            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
                                        )

                                )

                            [buyingAsset:protected] => ZuluCrypto\StellarSdk\XdrModel\Asset Object
                                (
                                    [type:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => 1
                                    [assetCode:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => BTCM
                                    [issuer:ZuluCrypto\StellarSdk\XdrModel\Asset:private] => ZuluCrypto\StellarSdk\XdrModel\AccountId Object
                                        (
                                            [accountIdString:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************HQ52
                                            [accountIdBytes:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => ******************************
                                            [keyType:ZuluCrypto\StellarSdk\XdrModel\AccountId:private] => 0
                                        )

                                )

                            [amount:protected] => ZuluCrypto\StellarSdk\Model\StellarAmount Object
                                (
                                    [stroops:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x07b4ac4949d8fb2c
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [stroopScaleBignum:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x00989680
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                    [maxSignedStroops64:protected] => phpseclib\Math\BigInteger Object
                                        (
                                            [value] => 0x7fffffffffffffff
                                            [engine] => internal (64-bit, OpenSSL)
                                        )

                                )

                            [price:protected] => ZuluCrypto\StellarSdk\XdrModel\Price Object
                                (
                                    [numerator:protected] => 83794
                                    [denominator:protected] => 5049
                                )

                            [offerId:protected] => 74263715
                            [sourceAccount:protected] => 
                            [type:protected] => 3
                        )

                )

        )

    [apiClient:ZuluCrypto\StellarSdk\Transaction\TransactionBuilder:private] => ZuluCrypto\StellarSdk\Horizon\ApiClient Object
        (
            [httpClient:protected] => GuzzleHttp\Client Object
                (
                    [config:GuzzleHttp\Client:private] => Array
                        (
                            [base_uri] => GuzzleHttp\Psr7\Uri Object
                                (
                                    [scheme:GuzzleHttp\Psr7\Uri:private] => https
                                    [userInfo:GuzzleHttp\Psr7\Uri:private] => 
                                    [host:GuzzleHttp\Psr7\Uri:private] => horizon.stellar.org
                                    [port:GuzzleHttp\Psr7\Uri:private] => 
                                    [path:GuzzleHttp\Psr7\Uri:private] => /
                                    [query:GuzzleHttp\Psr7\Uri:private] => 
                                    [fragment:GuzzleHttp\Psr7\Uri:private] => 
                                )

                            [exceptions] => 
                            [handler] => GuzzleHttp\HandlerStack Object
                                (
                                    [handler:GuzzleHttp\HandlerStack:private] => Closure Object
                                        (
                                            [static] => Array
                                                (
                                                    [default] => Closure Object
                                                        (
                                                            [static] => Array
                                                                (
                                                                    [default] => GuzzleHttp\Handler\CurlMultiHandler Object
                                                                        (
                                                                            [factory:GuzzleHttp\Handler\CurlMultiHandler:private] => GuzzleHttp\Handler\CurlFactory Object
                                                                                (
                                                                                    [handles:GuzzleHttp\Handler\CurlFactory:private] => Array
                                                                                        (
                                                                                        )

                                                                                    [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 50
                                                                                )

                                                                            [selectTimeout:GuzzleHttp\Handler\CurlMultiHandler:private] => 1
                                                                            [active:GuzzleHttp\Handler\CurlMultiHandler:private] => 
                                                                            [handles:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
                                                                                (
                                                                                )

                                                                            [delays:GuzzleHttp\Handler\CurlMultiHandler:private] => Array
                                                                                (
                                                                                )

                                                                        )

                                                                    [sync] => GuzzleHttp\Handler\CurlHandler Object
                                                                        (
                                                                            [factory:GuzzleHttp\Handler\CurlHandler:private] => GuzzleHttp\Handler\CurlFactory Object
                                                                                (
                                                                                    [handles:GuzzleHttp\Handler\CurlFactory:private] => Array
                                                                                        (
                                                                                        )

                                                                                    [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 3
                                                                                )

                                                                        )

                                                                )

                                                            [parameter] => Array
                                                                (
                                                                    [$request] => 
                                                                    [$options] => 
                                                                )

                                                        )

                                                    [streaming] => GuzzleHttp\Handler\StreamHandler Object
                                                        (
                                                            [lastHeaders:GuzzleHttp\Handler\StreamHandler:private] => Array
                                                                (
                                                                )

                                                        )

                                                )

                                            [parameter] => Array
                                                (
                                                    [$request] => 
                                                    [$options] => 
                                                )

                                        )

                                    [stack:GuzzleHttp\HandlerStack:private] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => http_errors
                                                )

                                            [1] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => allow_redirects
                                                )

                                            [2] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => cookies
                                                )

                                            [3] => Array
                                                (
                                                    [0] => Closure Object
                                                        (
                                                            [parameter] => Array
                                                                (
                                                                    [$handler] => 
                                                                )

                                                        )

                                                    [1] => prepare_body
                                                )

                                        )

                                    [cached:GuzzleHttp\HandlerStack:private] => 
                                )

                            [allow_redirects] => Array
                                (
                                    [max] => 5
                                    [protocols] => Array
                                        (
                                            [0] => http
                                            [1] => https
                                        )

                                    [strict] => 
                                    [referer] => 
                                    [track_redirects] => 
                                )

                            [http_errors] => 1
                            [decode_content] => 1
                            [verify] => 1
                            [cookies] => 
                            [headers] => Array
                                (
                                    [User-Agent] => GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u3
                                )

                        )

                )

            [baseUrl:protected] => https://horizon.stellar.org/
            [isTestnet:protected] => 
            [networkPassphrase:protected] => Public Global Stellar Network ; September 2015
        )

    [signingProvider:protected] => 
    [signatures:protected] => Array
        (
        )

    [sequenceNumber:protected] => 
)
```
